# @ stub AUDIOSES_1
# @ stub AUDIOSES_2
# @ stub AUDIOSES_3
# @ stub AUDIOSES_4
# @ stub AUDIOSES_5
# @ stub DllCanUnloadNow
# @ stub AUDIOSES_7
# @ stub DllGetActivationFactory
# @ stub DllGetClassObject
# @ stub DllRegisterServer
# @ stub DllUnregisterServer
