@ stdcall D3DX10CreateThreadPump(long long ptr)
@ stdcall D3DX10CheckVersion(long long)
@ stub D3DX10CompileFromFileA(str ptr ptr str str long long ptr ptr ptr ptr)
@ stub D3DX10CompileFromFileW(wstr ptr ptr str str long long ptr ptr ptr ptr)
@ stdcall D3DX10CompileFromMemory(ptr long str ptr ptr str str long long ptr ptr ptr ptr)
@ stub D3DX10CompileFromResourceA(long str str ptr ptr str str long long ptr ptr ptr ptr)
@ stub D3DX10CompileFromResourceW(long wstr wstr ptr ptr str str long long ptr ptr ptr ptr)
@ stub D3DX10ComputeNormalMap(ptr long long long ptr)
@ stub D3DX10CreateAsyncCompilerProcessor(str ptr ptr str str long long ptr ptr ptr)
@ stub D3DX10CreateAsyncEffectCreateProcessor(str ptr ptr str long long ptr ptr ptr ptr)
@ stub D3DX10CreateAsyncEffectPoolCreateProcessor(str ptr ptr str long long ptr ptr ptr)
@ stdcall D3DX10CreateAsyncFileLoaderA(str ptr)
@ stdcall D3DX10CreateAsyncFileLoaderW(wstr ptr)
@ stdcall D3DX10CreateAsyncMemoryLoader(ptr long ptr)
@ stdcall D3DX10CreateAsyncResourceLoaderA(long str ptr)
@ stdcall D3DX10CreateAsyncResourceLoaderW(long wstr ptr)
@ stub D3DX10CreateAsyncShaderPreprocessProcessor(str ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateAsyncShaderResourceViewProcessor(ptr ptr ptr)
@ stdcall D3DX10CreateAsyncTextureInfoProcessor(ptr ptr)
@ stdcall D3DX10CreateAsyncTextureProcessor(ptr ptr ptr)
@ stdcall D3DX10CreateDevice(ptr long long long ptr)
@ stdcall D3DX10CreateDeviceAndSwapChain(ptr long long long ptr ptr ptr)
@ stdcall D3DX10CreateEffectFromFileA(str ptr ptr str long long ptr ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectFromFileW(wstr ptr ptr str long long ptr ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectFromMemory(ptr long str ptr ptr str long long ptr ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectFromResourceA(long str str ptr ptr str long long ptr ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectFromResourceW(long wstr wstr ptr ptr str long long ptr ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectPoolFromFileA(str ptr ptr str long long ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectPoolFromFileW(wstr ptr ptr str long long ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateEffectPoolFromMemory(ptr long str ptr ptr str long long ptr ptr ptr ptr ptr)
@ stub D3DX10CreateEffectPoolFromResourceA(long str str ptr ptr str long long ptr ptr ptr ptr ptr)
@ stub D3DX10CreateEffectPoolFromResourceW(long wstr wstr ptr ptr str long long ptr ptr ptr ptr ptr)
@ stdcall D3DX10CreateFontA(ptr long long long long long long long long long str ptr)
@ stdcall D3DX10CreateFontIndirectA(ptr ptr ptr)
@ stdcall D3DX10CreateFontIndirectW(ptr ptr ptr)
@ stdcall D3DX10CreateFontW(ptr long long long long long long long long long wstr ptr)
@ stdcall D3DX10CreateMesh(ptr ptr long str long long long ptr)
@ stdcall D3DX10CreateShaderResourceViewFromFileA(ptr str ptr ptr ptr ptr)
@ stdcall D3DX10CreateShaderResourceViewFromFileW(ptr wstr ptr ptr ptr ptr)
@ stdcall D3DX10CreateShaderResourceViewFromMemory(ptr ptr long ptr ptr ptr ptr)
@ stdcall D3DX10CreateShaderResourceViewFromResourceA(ptr long str ptr ptr ptr ptr)
@ stdcall D3DX10CreateShaderResourceViewFromResourceW(ptr long wstr ptr ptr ptr ptr)
@ stub D3DX10CreateSkinInfo(ptr)
@ stdcall D3DX10CreateSprite(ptr long ptr)
@ stdcall D3DX10CreateTextureFromFileA(ptr str ptr ptr ptr ptr)
@ stdcall D3DX10CreateTextureFromFileW(ptr wstr ptr ptr ptr ptr)
@ stdcall D3DX10CreateTextureFromMemory(ptr ptr long ptr ptr ptr ptr)
@ stdcall D3DX10CreateTextureFromResourceA(ptr long str ptr ptr ptr ptr)
@ stdcall D3DX10CreateTextureFromResourceW(ptr long wstr ptr ptr ptr ptr)
@ stdcall D3DX10FilterTexture(ptr long long)
@ stdcall D3DX10GetFeatureLevel1(ptr ptr)
@ stdcall D3DX10GetImageInfoFromFileA(str ptr ptr ptr)
@ stdcall D3DX10GetImageInfoFromFileW(wstr ptr ptr ptr)
@ stdcall D3DX10GetImageInfoFromMemory(ptr long ptr ptr ptr)
@ stdcall D3DX10GetImageInfoFromResourceA(long str ptr ptr ptr)
@ stdcall D3DX10GetImageInfoFromResourceW(long wstr ptr ptr ptr)
@ stdcall D3DX10LoadTextureFromTexture(ptr ptr ptr)
@ stub D3DX10PreprocessShaderFromFileA(str ptr ptr ptr ptr ptr)
@ stub D3DX10PreprocessShaderFromFileW(wstr ptr ptr ptr ptr ptr)
@ stdcall D3DX10PreprocessShaderFromMemory(ptr long str ptr ptr ptr ptr ptr ptr)
@ stub D3DX10PreprocessShaderFromResourceA(long str str ptr ptr ptr ptr ptr)
@ stub D3DX10PreprocessShaderFromResourceW(long wstr wstr ptr ptr ptr ptr ptr)
@ stub D3DX10SHProjectCubeMap(long ptr ptr ptr ptr)
@ stdcall D3DX10SaveTextureToFileA(ptr ptr str)
@ stdcall D3DX10SaveTextureToFileW(ptr ptr wstr)
@ stdcall D3DX10SaveTextureToMemory(ptr ptr ptr long)
@ stdcall D3DX10UnsetAllDeviceObjects(ptr)
@ stdcall D3DXBoxBoundProbe(ptr ptr ptr ptr)
@ stdcall D3DXColorAdjustContrast(ptr ptr float)
@ stdcall D3DXColorAdjustSaturation(ptr ptr float)
@ stdcall D3DXComputeBoundingBox(ptr long long ptr ptr)
@ stdcall D3DXComputeBoundingSphere(ptr long long ptr ptr)
@ stdcall D3DXCpuOptimizations(long)
@ stdcall D3DXCreateMatrixStack(long ptr)
@ stdcall D3DXFloat16To32Array(ptr ptr long)
@ stdcall D3DXFloat32To16Array(ptr ptr long)
@ stdcall D3DXFresnelTerm(float float)
@ stdcall D3DXIntersectTri(ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall D3DXMatrixAffineTransformation2D(ptr float ptr float ptr)
@ stdcall D3DXMatrixAffineTransformation(ptr float ptr ptr ptr)
@ stdcall D3DXMatrixDecompose(ptr ptr ptr ptr)
@ stdcall D3DXMatrixDeterminant(ptr)
@ stdcall D3DXMatrixInverse(ptr ptr ptr)
@ stdcall D3DXMatrixLookAtLH(ptr ptr ptr ptr)
@ stdcall D3DXMatrixLookAtRH(ptr ptr ptr ptr)
@ stdcall D3DXMatrixMultiply(ptr ptr ptr)
@ stdcall D3DXMatrixMultiplyTranspose(ptr ptr ptr)
@ stdcall D3DXMatrixOrthoLH(ptr float float float float)
@ stdcall D3DXMatrixOrthoOffCenterLH(ptr float float float float float float)
@ stdcall D3DXMatrixOrthoOffCenterRH(ptr float float float float float float)
@ stdcall D3DXMatrixOrthoRH(ptr float float float float)
@ stdcall D3DXMatrixPerspectiveFovLH(ptr float float float float)
@ stdcall D3DXMatrixPerspectiveFovRH(ptr float float float float)
@ stdcall D3DXMatrixPerspectiveLH(ptr float float float float)
@ stdcall D3DXMatrixPerspectiveOffCenterLH(ptr float float float float float float)
@ stdcall D3DXMatrixPerspectiveOffCenterRH(ptr float float float float float float)
@ stdcall D3DXMatrixPerspectiveRH(ptr float float float float)
@ stdcall D3DXMatrixReflect(ptr ptr)
@ stdcall D3DXMatrixRotationAxis(ptr ptr float)
@ stdcall D3DXMatrixRotationQuaternion(ptr ptr)
@ stdcall D3DXMatrixRotationX(ptr float)
@ stdcall D3DXMatrixRotationY(ptr float)
@ stdcall D3DXMatrixRotationYawPitchRoll(ptr float float float)
@ stdcall D3DXMatrixRotationZ(ptr float)
@ stdcall D3DXMatrixScaling(ptr float float float)
@ stdcall D3DXMatrixShadow(ptr ptr ptr)
@ stdcall D3DXMatrixTransformation2D(ptr ptr float ptr ptr float ptr)
@ stdcall D3DXMatrixTransformation(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall D3DXMatrixTranslation(ptr float float float)
@ stdcall D3DXMatrixTranspose(ptr ptr)
@ stdcall D3DXPlaneFromPointNormal(ptr ptr ptr)
@ stdcall D3DXPlaneFromPoints(ptr ptr ptr ptr)
@ stdcall D3DXPlaneIntersectLine(ptr ptr ptr ptr)
@ stdcall D3DXPlaneNormalize(ptr ptr)
@ stdcall D3DXPlaneTransform(ptr ptr ptr)
@ stdcall D3DXPlaneTransformArray(ptr long ptr long ptr long)
@ stdcall D3DXQuaternionBaryCentric(ptr ptr ptr ptr float float)
@ stdcall D3DXQuaternionExp(ptr ptr)
@ stdcall D3DXQuaternionInverse(ptr ptr)
@ stdcall D3DXQuaternionLn(ptr ptr)
@ stdcall D3DXQuaternionMultiply(ptr ptr ptr)
@ stdcall D3DXQuaternionNormalize(ptr ptr)
@ stdcall D3DXQuaternionRotationAxis(ptr ptr float)
@ stdcall D3DXQuaternionRotationMatrix(ptr ptr)
@ stdcall D3DXQuaternionRotationYawPitchRoll(ptr float float float)
@ stdcall D3DXQuaternionSlerp(ptr ptr ptr float)
@ stdcall D3DXQuaternionSquad(ptr ptr ptr ptr ptr float)
@ stdcall D3DXQuaternionSquadSetup(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall D3DXQuaternionToAxisAngle(ptr ptr ptr)
@ stdcall D3DXSHAdd(ptr long ptr ptr)
@ stdcall D3DXSHDot(long ptr ptr)
@ stdcall D3DXSHEvalConeLight(long ptr float float float float ptr ptr ptr)
@ stdcall D3DXSHEvalDirection(ptr long ptr)
@ stdcall D3DXSHEvalDirectionalLight(long ptr float float float ptr ptr ptr)
@ stdcall D3DXSHEvalHemisphereLight(long ptr int128 int128 ptr ptr ptr)
@ stdcall D3DXSHEvalSphericalLight(long ptr long long long long ptr ptr ptr)
@ stdcall D3DXSHMultiply2(ptr ptr ptr)
@ stdcall D3DXSHMultiply3(ptr ptr ptr)
@ stdcall D3DXSHMultiply4(ptr ptr ptr)
@ stub D3DXSHMultiply5(ptr ptr ptr)
@ stub D3DXSHMultiply6(ptr ptr ptr)
@ stdcall D3DXSHRotate(ptr long ptr ptr)
@ stdcall D3DXSHRotateZ(ptr long float ptr)
@ stdcall D3DXSHScale(ptr long ptr float)
@ stdcall D3DXSphereBoundProbe(ptr float ptr ptr)
@ stdcall D3DXVec2BaryCentric(ptr ptr ptr ptr float float)
@ stdcall D3DXVec2CatmullRom(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec2Hermite(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec2Normalize(ptr ptr)
@ stdcall D3DXVec2Transform(ptr ptr ptr)
@ stdcall D3DXVec2TransformArray(ptr long ptr long ptr long)
@ stdcall D3DXVec2TransformCoord(ptr ptr ptr)
@ stdcall D3DXVec2TransformCoordArray(ptr long ptr long ptr long)
@ stdcall D3DXVec2TransformNormal(ptr ptr ptr)
@ stdcall D3DXVec2TransformNormalArray(ptr long ptr long ptr long)
@ stdcall D3DXVec3BaryCentric(ptr ptr ptr ptr float float)
@ stdcall D3DXVec3CatmullRom(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec3Hermite(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec3Normalize(ptr ptr)
@ stdcall D3DXVec3Project(ptr ptr ptr ptr ptr ptr)
@ stdcall D3DXVec3ProjectArray(ptr long ptr long ptr ptr ptr ptr long)
@ stdcall D3DXVec3Transform(ptr ptr ptr)
@ stdcall D3DXVec3TransformArray(ptr long ptr long ptr long)
@ stdcall D3DXVec3TransformCoord(ptr ptr ptr)
@ stdcall D3DXVec3TransformCoordArray(ptr long ptr long ptr long)
@ stdcall D3DXVec3TransformNormal(ptr ptr ptr)
@ stdcall D3DXVec3TransformNormalArray(ptr long ptr long ptr long)
@ stdcall D3DXVec3Unproject(ptr ptr ptr ptr ptr ptr)
@ stdcall D3DXVec3UnprojectArray(ptr long ptr long ptr ptr ptr ptr long)
@ stdcall D3DXVec4BaryCentric(ptr ptr ptr ptr float float)
@ stdcall D3DXVec4CatmullRom(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec4Cross(ptr ptr ptr ptr)
@ stdcall D3DXVec4Hermite(ptr ptr ptr ptr ptr float)
@ stdcall D3DXVec4Normalize(ptr ptr)
@ stdcall D3DXVec4Transform(ptr ptr ptr)
@ stdcall D3DXVec4TransformArray(ptr long ptr long ptr long)
