/*
 * Copyright 2018 Józef Kucia for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

typedef void (__cdecl *gl_texture_callback)(unsigned int gl_texture, const void *data, unsigned int data_size);

import "d3d11.idl";

[
    object,
    local,
    uuid(267dc993-d15e-4015-aaac-b7559e226cc3)
]
interface IWineD3D11Texture2D : ID3D11Texture2D
{
    void access_gl_texture(gl_texture_callback callback, const void *data, unsigned int data_size);
}

typedef void (__cdecl *user_cs_callback)(const void *data, unsigned int data_size);

[
    object,
    local,
    uuid(8f02de7e-d55d-457b-9423-83456e49c58a)
]
interface IWineD3D11Device : IUnknown
{
    void run_on_command_stream(user_cs_callback callback, const void *data, unsigned int data_size);
}
