@ cdecl xessDestroyContext(ptr)
@ cdecl xessGetProperties(ptr ptr ptr)
@ cdecl xessGetInputResolution(ptr ptr long ptr)
@ cdecl xessGetOptimalInputResolution(ptr ptr long ptr ptr ptr)
@ cdecl xessGetJitterScale(ptr ptr ptr)
@ cdecl xessGetVelocityScale(ptr ptr ptr)
@ cdecl xessGetExposureMultiplier(ptr ptr)
@ cdecl xessGetMaxResponsiveMaskValue(ptr ptr)
@ cdecl xessGetIntelXeFXVersion(ptr ptr)
@ cdecl xessIsOptimalDriver(ptr)
@ cdecl xessGetVersion(ptr)
@ cdecl xessSetLoggingCallback(ptr long ptr)
@ cdecl xessSetVelocityScale(ptr float float)
@ cdecl xessSetJitterScale(ptr float float)
@ cdecl xessSetExposureMultiplier(ptr float)
@ cdecl xessSetMaxResponsiveMaskValue(ptr float)
@ cdecl xessSetContextParameterF(ptr long float)
@ cdecl xessGetPipelineBuildStatus(ptr)
@ cdecl xessForceLegacyScaleFactors(ptr long)
@ cdecl xessVKGetRequiredInstanceExtensions(ptr ptr ptr)
@ cdecl xessVKGetRequiredDeviceExtensions(ptr ptr ptr ptr)
@ cdecl xessVKGetRequiredDeviceFeatures(ptr ptr ptr)
@ cdecl xessVKCreateContext(ptr ptr ptr ptr)
@ cdecl xessVKBuildPipelines(ptr int64 long long)
@ cdecl xessVKInit(ptr ptr)
@ cdecl xessVKGetInitParams(ptr ptr)
@ cdecl xessVKExecute(ptr ptr ptr)
@ cdecl xessD3D12CreateContext(ptr ptr)
@ cdecl xessD3D12Init(ptr ptr)
@ cdecl xessD3D12GetInitParams(ptr ptr)
@ cdecl xessD3D12Execute(ptr ptr ptr)
@ cdecl xessD3D12BuildPipelines(ptr ptr long long)
@ cdecl xessSelectNetworkModel(ptr long)
@ cdecl xessStartDump(ptr ptr)
@ cdecl xessGetProfilingData(ptr ptr)
