# atl_android Makefile.am
lib_LTLIBRARIES = libatl_android.la
libatl_android_la_SOURCES = \
	asset_manager.c \
	bitmap.c \
	configuration.c \
	input.c \
	looper.c \
	media.c \
	native_window.c \
	sensor.c \
	trace.c \
	wayland_server.c \
	atl_android.c

# Add any required CFLAGS or dependencies here
AM_CFLAGS = -I$(top_srcdir)/include
