#@ stub CloseDefaultICUGroupingLetters
#@ stub GetDefaultICUGroupingLetters
#@ stub GetICUGroupingLetter
#@ stub SortCloseHandle
#@ stub SortGetHandle
#@ stub SortGetSearchKey
#@ stub UCNV_FROM_U_CALLBACK_ESCAPE
#@ stub UCNV_FROM_U_CALLBACK_SKIP
#@ stub UCNV_FROM_U_CALLBACK_STOP
#@ stub UCNV_FROM_U_CALLBACK_SUBSTITUTE
#@ stub UCNV_TO_U_CALLBACK_ESCAPE
#@ stub UCNV_TO_U_CALLBACK_SKIP
#@ stub UCNV_TO_U_CALLBACK_STOP
#@ stub UCNV_TO_U_CALLBACK_SUBSTITUTE
#@ stub u_UCharsToChars
#@ stub u_austrcpy
#@ stub u_austrncpy
#@ stub u_catclose
#@ stub u_catgets
#@ stub u_catopen
#@ stub u_charAge
#@ stub u_charDigitValue
#@ stub u_charDirection
#@ stub u_charFromName
#@ stub u_charMirror
#@ stub u_charName
#@ stub u_charType
#@ stub u_charsToUChars
#@ stub u_cleanup
#@ stub u_countChar32
#@ stub u_digit
#@ stub u_enumCharNames
#@ stub u_enumCharTypes
#@ stub u_errorName
#@ stub u_foldCase
#@ stub u_forDigit
#@ stub u_formatMessage
#@ stub u_formatMessageWithError
#@ stub u_getBidiPairedBracket
#@ stub u_getBinaryPropertySet
#@ stub u_getCombiningClass
#@ stub u_getDataVersion
#@ stub u_getFC_NFKC_Closure
#@ stub u_getIntPropertyMap
#@ stub u_getIntPropertyMaxValue
#@ stub u_getIntPropertyMinValue
#@ stub u_getIntPropertyValue
#@ stub u_getNumericValue
#@ stub u_getPropertyEnum
#@ stub u_getPropertyName
#@ stub u_getPropertyValueEnum
#@ stub u_getPropertyValueName
#@ stub u_getUnicodeVersion
#@ stub u_getVersion
#@ stub u_hasBinaryProperty
#@ stub u_init
#@ stub u_isIDIgnorable
#@ stub u_isIDPart
#@ stub u_isIDStart
#@ stub u_isISOControl
#@ stub u_isJavaIDPart
#@ stub u_isJavaIDStart
#@ stub u_isJavaSpaceChar
#@ stub u_isMirrored
#@ stub u_isUAlphabetic
#@ stub u_isULowercase
#@ stub u_isUUppercase
#@ stub u_isUWhiteSpace
#@ stub u_isWhitespace
#@ stub u_isalnum
#@ stub u_isalpha
#@ stub u_isbase
#@ stub u_isblank
#@ stub u_iscntrl
#@ stub u_isdefined
#@ stub u_isdigit
#@ stub u_isgraph
#@ stub u_islower
#@ stub u_isprint
#@ stub u_ispunct
#@ stub u_isspace
#@ stub u_istitle
#@ stub u_isupper
#@ stub u_isxdigit
#@ stub u_memcasecmp
#@ stub u_memchr
#@ stub u_memchr32
#@ stub u_memcmp
#@ stub u_memcmpCodePointOrder
#@ stub u_memcpy
#@ stub u_memmove
#@ stub u_memrchr
#@ stub u_memrchr32
#@ stub u_memset
#@ stub u_parseMessage
#@ stub u_parseMessageWithError
#@ stub u_setMemoryFunctions
#@ stub u_shapeArabic
#@ stub u_strCaseCompare
#@ stub u_strCompare
#@ stub u_strCompareIter
#@ stub u_strFindFirst
#@ stub u_strFindLast
#@ stub u_strFoldCase
#@ stub u_strFromJavaModifiedUTF8WithSub
#@ stub u_strFromUTF32
#@ stub u_strFromUTF32WithSub
#@ stub u_strFromUTF8
#@ stub u_strFromUTF8Lenient
#@ stub u_strFromUTF8WithSub
#@ stub u_strFromWCS
#@ stub u_strHasMoreChar32Than
#@ stub u_strToJavaModifiedUTF8
#@ stub u_strToLower
#@ stub u_strToTitle
#@ stub u_strToUTF32
#@ stub u_strToUTF32WithSub
#@ stub u_strToUTF8
#@ stub u_strToUTF8WithSub
#@ stub u_strToUpper
#@ stub u_strToWCS
#@ stub u_strcasecmp
#@ stub u_strcat
#@ stub u_strchr
#@ stub u_strchr32
#@ stub u_strcmp
#@ stub u_strcmpCodePointOrder
#@ stub u_strcpy
#@ stub u_strcspn
#@ stub u_strlen
#@ stub u_strncasecmp
#@ stub u_strncat
#@ stub u_strncmp
#@ stub u_strncmpCodePointOrder
#@ stub u_strncpy
#@ stub u_strpbrk
#@ stub u_strrchr
#@ stub u_strrchr32
#@ stub u_strrstr
#@ stub u_strspn
#@ stub u_strstr
#@ stub u_strtok_r
#@ stub u_tolower
#@ stub u_totitle
#@ stub u_toupper
#@ stub u_uastrcpy
#@ stub u_uastrncpy
#@ stub u_unescape
#@ stub u_unescapeAt
#@ stub u_versionFromString
#@ stub u_versionFromUString
#@ stub u_versionToString
#@ stub u_vformatMessage
#@ stub u_vformatMessageWithError
#@ stub u_vparseMessage
#@ stub u_vparseMessageWithError
#@ stub ubidi_close
#@ stub ubidi_countParagraphs
#@ stub ubidi_countRuns
#@ stub ubidi_getBaseDirection
#@ stub ubidi_getClassCallback
#@ stub ubidi_getCustomizedClass
#@ stub ubidi_getDirection
#@ stub ubidi_getLength
#@ stub ubidi_getLevelAt
#@ stub ubidi_getLevels
#@ stub ubidi_getLogicalIndex
#@ stub ubidi_getLogicalMap
#@ stub ubidi_getLogicalRun
#@ stub ubidi_getParaLevel
#@ stub ubidi_getParagraph
#@ stub ubidi_getParagraphByIndex
#@ stub ubidi_getProcessedLength
#@ stub ubidi_getReorderingMode
#@ stub ubidi_getReorderingOptions
#@ stub ubidi_getResultLength
#@ stub ubidi_getText
#@ stub ubidi_getVisualIndex
#@ stub ubidi_getVisualMap
#@ stub ubidi_getVisualRun
#@ stub ubidi_invertMap
#@ stub ubidi_isInverse
#@ stub ubidi_isOrderParagraphsLTR
#@ stub ubidi_open
#@ stub ubidi_openSized
#@ stub ubidi_orderParagraphsLTR
#@ stub ubidi_reorderLogical
#@ stub ubidi_reorderVisual
#@ stub ubidi_setClassCallback
#@ stub ubidi_setContext
#@ stub ubidi_setInverse
#@ stub ubidi_setLine
#@ stub ubidi_setPara
#@ stub ubidi_setReorderingMode
#@ stub ubidi_setReorderingOptions
#@ stub ubidi_writeReordered
#@ stub ubidi_writeReverse
#@ stub ubiditransform_close
#@ stub ubiditransform_open
#@ stub ubiditransform_transform
#@ stub ublock_getCode
#@ stub ubrk_close
#@ stub ubrk_countAvailable
#@ stub ubrk_current
#@ stub ubrk_first
#@ stub ubrk_following
#@ stub ubrk_getAvailable
#@ stub ubrk_getBinaryRules
#@ stub ubrk_getLocaleByType
#@ stub ubrk_getRuleStatus
#@ stub ubrk_getRuleStatusVec
#@ stub ubrk_isBoundary
#@ stub ubrk_last
#@ stub ubrk_next
#@ stub ubrk_open
#@ stub ubrk_openBinaryRules
#@ stub ubrk_openRules
#@ stub ubrk_preceding
#@ stub ubrk_previous
#@ stub ubrk_refreshUText
#@ stub ubrk_safeClone
#@ stub ubrk_setText
#@ stub ubrk_setUText
#@ stub ucal_add
#@ stub ucal_clear
#@ stub ucal_clearField
#@ stub ucal_clone
#@ stub ucal_close
#@ stub ucal_countAvailable
#@ stub ucal_equivalentTo
#@ stub ucal_get
#@ stub ucal_getAttribute
#@ stub ucal_getAvailable
#@ stub ucal_getCanonicalTimeZoneID
#@ stub ucal_getDSTSavings
#@ stub ucal_getDayOfWeekType
#@ stub ucal_getDefaultTimeZone
#@ stub ucal_getFieldDifference
#@ stub ucal_getGregorianChange
#@ stub ucal_getHostTimeZone
#@ stub ucal_getKeywordValuesForLocale
#@ stub ucal_getLimit
#@ stub ucal_getLocaleByType
#@ stub ucal_getMillis
#@ stub ucal_getNow
#@ stub ucal_getTZDataVersion
#@ stub ucal_getTimeZoneDisplayName
#@ stub ucal_getTimeZoneID
#@ stub ucal_getTimeZoneIDForWindowsID
#@ stub ucal_getTimeZoneTransitionDate
#@ stub ucal_getType
#@ stub ucal_getWeekendTransition
#@ stub ucal_getWindowsTimeZoneID
#@ stub ucal_inDaylightTime
#@ stub ucal_isSet
#@ stub ucal_isWeekend
#@ stub ucal_open
#@ stub ucal_openCountryTimeZones
#@ stub ucal_openTimeZoneIDEnumeration
#@ stub ucal_openTimeZones
#@ stub ucal_roll
#@ stub ucal_set
#@ stub ucal_setAttribute
#@ stub ucal_setDate
#@ stub ucal_setDateTime
#@ stub ucal_setDefaultTimeZone
#@ stub ucal_setGregorianChange
#@ stub ucal_setMillis
#@ stub ucal_setTimeZone
#@ stub ucasemap_close
#@ stub ucasemap_getBreakIterator
#@ stub ucasemap_getLocale
#@ stub ucasemap_getOptions
#@ stub ucasemap_open
#@ stub ucasemap_setBreakIterator
#@ stub ucasemap_setLocale
#@ stub ucasemap_setOptions
#@ stub ucasemap_toTitle
#@ stub ucasemap_utf8FoldCase
#@ stub ucasemap_utf8ToLower
#@ stub ucasemap_utf8ToTitle
#@ stub ucasemap_utf8ToUpper
#@ stub ucfpos_close
#@ stub ucfpos_constrainCategory
#@ stub ucfpos_constrainField
#@ stub ucfpos_getCategory
#@ stub ucfpos_getField
#@ stub ucfpos_getIndexes
#@ stub ucfpos_getInt64IterationContext
#@ stub ucfpos_matchesField
#@ stub ucfpos_open
#@ stub ucfpos_reset
#@ stub ucfpos_setInt64IterationContext
#@ stub ucfpos_setState
#@ stub ucnv_cbFromUWriteBytes
#@ stub ucnv_cbFromUWriteSub
#@ stub ucnv_cbFromUWriteUChars
#@ stub ucnv_cbToUWriteSub
#@ stub ucnv_cbToUWriteUChars
#@ stub ucnv_close
#@ stub ucnv_compareNames
#@ stub ucnv_convert
#@ stub ucnv_convertEx
#@ stub ucnv_countAliases
#@ stub ucnv_countAvailable
#@ stub ucnv_countStandards
#@ stub ucnv_detectUnicodeSignature
#@ stub ucnv_fixFileSeparator
#@ stub ucnv_flushCache
#@ stub ucnv_fromAlgorithmic
#@ stub ucnv_fromUChars
#@ stub ucnv_fromUCountPending
#@ stub ucnv_fromUnicode
#@ stub ucnv_getAlias
#@ stub ucnv_getAliases
#@ stub ucnv_getAvailableName
#@ stub ucnv_getCCSID
#@ stub ucnv_getCanonicalName
#@ stub ucnv_getDefaultName
#@ stub ucnv_getDisplayName
#@ stub ucnv_getFromUCallBack
#@ stub ucnv_getInvalidChars
#@ stub ucnv_getInvalidUChars
#@ stub ucnv_getMaxCharSize
#@ stub ucnv_getMinCharSize
#@ stub ucnv_getName
#@ stub ucnv_getNextUChar
#@ stub ucnv_getPlatform
#@ stub ucnv_getStandard
#@ stub ucnv_getStandardName
#@ stub ucnv_getStarters
#@ stub ucnv_getSubstChars
#@ stub ucnv_getToUCallBack
#@ stub ucnv_getType
#@ stub ucnv_getUnicodeSet
#@ stub ucnv_isAmbiguous
#@ stub ucnv_isFixedWidth
#@ stub ucnv_open
#@ stub ucnv_openAllNames
#@ stub ucnv_openCCSID
#@ stub ucnv_openPackage
#@ stub ucnv_openStandardNames
#@ stub ucnv_openU
#@ stub ucnv_reset
#@ stub ucnv_resetFromUnicode
#@ stub ucnv_resetToUnicode
#@ stub ucnv_safeClone
#@ stub ucnv_setDefaultName
#@ stub ucnv_setFallback
#@ stub ucnv_setFromUCallBack
#@ stub ucnv_setSubstChars
#@ stub ucnv_setSubstString
#@ stub ucnv_setToUCallBack
#@ stub ucnv_toAlgorithmic
#@ stub ucnv_toUChars
#@ stub ucnv_toUCountPending
#@ stub ucnv_toUnicode
#@ stub ucnv_usesFallback
#@ stub ucnvsel_close
#@ stub ucnvsel_open
#@ stub ucnvsel_openFromSerialized
#@ stub ucnvsel_selectForString
#@ stub ucnvsel_selectForUTF8
#@ stub ucnvsel_serialize
#@ stub ucol_cloneBinary
#@ stub ucol_close
#@ stub ucol_closeElements
#@ stub ucol_countAvailable
#@ stub ucol_equal
#@ stub ucol_getAttribute
#@ stub ucol_getAvailable
#@ stub ucol_getBound
#@ stub ucol_getContractionsAndExpansions
#@ stub ucol_getDisplayName
#@ stub ucol_getEquivalentReorderCodes
#@ stub ucol_getFunctionalEquivalent
#@ stub ucol_getKeywordValues
#@ stub ucol_getKeywordValuesForLocale
#@ stub ucol_getKeywords
#@ stub ucol_getLocaleByType
#@ stub ucol_getMaxExpansion
#@ stub ucol_getMaxVariable
#@ stub ucol_getOffset
#@ stub ucol_getReorderCodes
#@ stub ucol_getRules
#@ stub ucol_getRulesEx
#@ stub ucol_getSortKey
#@ stub ucol_getStrength
#@ stub ucol_getTailoredSet
#@ stub ucol_getUCAVersion
#@ stub ucol_getVariableTop
#@ stub ucol_getVersion
#@ stub ucol_greater
#@ stub ucol_greaterOrEqual
#@ stub ucol_keyHashCode
#@ stub ucol_mergeSortkeys
#@ stub ucol_next
#@ stub ucol_nextSortKeyPart
#@ stub ucol_open
#@ stub ucol_openAvailableLocales
#@ stub ucol_openBinary
#@ stub ucol_openElements
#@ stub ucol_openRules
#@ stub ucol_previous
#@ stub ucol_primaryOrder
#@ stub ucol_reset
#@ stub ucol_safeClone
#@ stub ucol_secondaryOrder
#@ stub ucol_setAttribute
#@ stub ucol_setMaxVariable
#@ stub ucol_setOffset
#@ stub ucol_setReorderCodes
#@ stub ucol_setStrength
#@ stub ucol_setText
#@ stub ucol_strcoll
#@ stub ucol_strcollIter
#@ stub ucol_strcollUTF8
#@ stub ucol_tertiaryOrder
#@ stub ucpmap_get
#@ stub ucpmap_getRange
#@ stub ucptrie_close
#@ stub ucptrie_get
#@ stub ucptrie_getRange
#@ stub ucptrie_getType
#@ stub ucptrie_getValueWidth
#@ stub ucptrie_internalSmallIndex
#@ stub ucptrie_internalSmallU8Index
#@ stub ucptrie_internalU8PrevIndex
#@ stub ucptrie_openFromBinary
#@ stub ucptrie_toBinary
#@ stub ucsdet_close
#@ stub ucsdet_detect
#@ stub ucsdet_detectAll
#@ stub ucsdet_enableInputFilter
#@ stub ucsdet_getAllDetectableCharsets
#@ stub ucsdet_getConfidence
#@ stub ucsdet_getLanguage
#@ stub ucsdet_getName
#@ stub ucsdet_getUChars
#@ stub ucsdet_isInputFilterEnabled
#@ stub ucsdet_open
#@ stub ucsdet_setDeclaredEncoding
#@ stub ucsdet_setText
#@ stub ucurr_countCurrencies
#@ stub ucurr_forLocale
#@ stub ucurr_forLocaleAndDate
#@ stub ucurr_getDefaultFractionDigits
#@ stub ucurr_getDefaultFractionDigitsForUsage
#@ stub ucurr_getKeywordValuesForLocale
#@ stub ucurr_getName
#@ stub ucurr_getNumericCode
#@ stub ucurr_getPluralName
#@ stub ucurr_getRoundingIncrement
#@ stub ucurr_getRoundingIncrementForUsage
#@ stub ucurr_isAvailable
#@ stub ucurr_openISOCurrencies
#@ stub ucurr_register
#@ stub ucurr_unregister
#@ stub udat_adoptNumberFormat
#@ stub udat_adoptNumberFormatForFields
#@ stub udat_applyPattern
#@ stub udat_clone
#@ stub udat_close
#@ stub udat_countAvailable
#@ stub udat_countSymbols
#@ stub udat_format
#@ stub udat_formatCalendar
#@ stub udat_formatCalendarForFields
#@ stub udat_formatForFields
#@ stub udat_get2DigitYearStart
#@ stub udat_getAvailable
#@ stub udat_getBooleanAttribute
#@ stub udat_getCalendar
#@ stub udat_getContext
#@ stub udat_getLocaleByType
#@ stub udat_getNumberFormat
#@ stub udat_getNumberFormatForField
#@ stub udat_getSymbols
#@ stub udat_isLenient
#@ stub udat_open
#@ stub udat_parse
#@ stub udat_parseCalendar
#@ stub udat_set2DigitYearStart
#@ stub udat_setBooleanAttribute
#@ stub udat_setCalendar
#@ stub udat_setContext
#@ stub udat_setLenient
#@ stub udat_setNumberFormat
#@ stub udat_setSymbols
#@ stub udat_toCalendarDateField
#@ stub udat_toPattern
#@ stub udatpg_addPattern
#@ stub udatpg_clone
#@ stub udatpg_close
#@ stub udatpg_getAppendItemFormat
#@ stub udatpg_getAppendItemName
#@ stub udatpg_getBaseSkeleton
#@ stub udatpg_getBestPattern
#@ stub udatpg_getBestPatternWithOptions
#@ stub udatpg_getDateTimeFormat
#@ stub udatpg_getDecimal
#@ stub udatpg_getFieldDisplayName
#@ stub udatpg_getPatternForSkeleton
#@ stub udatpg_getSkeleton
#@ stub udatpg_open
#@ stub udatpg_openBaseSkeletons
#@ stub udatpg_openEmpty
#@ stub udatpg_openSkeletons
#@ stub udatpg_replaceFieldTypes
#@ stub udatpg_replaceFieldTypesWithOptions
#@ stub udatpg_setAppendItemFormat
#@ stub udatpg_setAppendItemName
#@ stub udatpg_setDateTimeFormat
#@ stub udatpg_setDecimal
#@ stub udtitvfmt_close
#@ stub udtitvfmt_closeResult
#@ stub udtitvfmt_format
#@ stub udtitvfmt_open
#@ stub udtitvfmt_openResult
#@ stub udtitvfmt_resultAsValue
#@ stub uenum_close
#@ stub uenum_count
#@ stub uenum_next
#@ stub uenum_openCharStringsEnumeration
#@ stub uenum_openUCharStringsEnumeration
#@ stub uenum_reset
#@ stub uenum_unext
#@ stub ufieldpositer_close
#@ stub ufieldpositer_next
#@ stub ufieldpositer_open
#@ stub ufmt_close
#@ stub ufmt_getArrayItemByIndex
#@ stub ufmt_getArrayLength
#@ stub ufmt_getDate
#@ stub ufmt_getDecNumChars
#@ stub ufmt_getDouble
#@ stub ufmt_getInt64
#@ stub ufmt_getLong
#@ stub ufmt_getObject
#@ stub ufmt_getType
#@ stub ufmt_getUChars
#@ stub ufmt_isNumeric
#@ stub ufmt_open
#@ stub ufmtval_getString
#@ stub ufmtval_nextPosition
#@ stub ugender_getInstance
#@ stub ugender_getListGender
#@ stub uidna_close
#@ stub uidna_labelToASCII
#@ stub uidna_labelToASCII_UTF8
#@ stub uidna_labelToUnicode
#@ stub uidna_labelToUnicodeUTF8
#@ stub uidna_nameToASCII
#@ stub uidna_nameToASCII_UTF8
#@ stub uidna_nameToUnicode
#@ stub uidna_nameToUnicodeUTF8
#@ stub uidna_openUTS46
#@ stub uiter_current32
#@ stub uiter_getState
#@ stub uiter_next32
#@ stub uiter_previous32
#@ stub uiter_setState
#@ stub uiter_setString
#@ stub uiter_setUTF16BE
#@ stub uiter_setUTF8
#@ stub uldn_close
#@ stub uldn_getContext
#@ stub uldn_getDialectHandling
#@ stub uldn_getLocale
#@ stub uldn_keyDisplayName
#@ stub uldn_keyValueDisplayName
#@ stub uldn_languageDisplayName
#@ stub uldn_localeDisplayName
#@ stub uldn_open
#@ stub uldn_openForContext
#@ stub uldn_regionDisplayName
#@ stub uldn_scriptCodeDisplayName
#@ stub uldn_scriptDisplayName
#@ stub uldn_variantDisplayName
#@ stub ulistfmt_close
#@ stub ulistfmt_closeResult
#@ stub ulistfmt_format
#@ stub ulistfmt_formatStringsToResult
#@ stub ulistfmt_open
#@ stub ulistfmt_openForType
#@ stub ulistfmt_openResult
#@ stub ulistfmt_resultAsValue
#@ stub uloc_acceptLanguage
#@ stub uloc_acceptLanguageFromHTTP
#@ stub uloc_addLikelySubtags
#@ stub uloc_canonicalize
#@ stub uloc_countAvailable
#@ stub uloc_forLanguageTag
#@ stub uloc_getAvailable
#@ stub uloc_getBaseName
#@ stub uloc_getCharacterOrientation
#@ stub uloc_getCountry
#@ stub uloc_getDefault
#@ stub uloc_getDisplayCountry
#@ stub uloc_getDisplayKeyword
#@ stub uloc_getDisplayKeywordValue
#@ stub uloc_getDisplayLanguage
#@ stub uloc_getDisplayName
#@ stub uloc_getDisplayScript
#@ stub uloc_getDisplayVariant
#@ stub uloc_getISO3Country
#@ stub uloc_getISO3Language
#@ stub uloc_getISOCountries
#@ stub uloc_getISOLanguages
#@ stub uloc_getKeywordValue
#@ stub uloc_getLCID
#@ stub uloc_getLanguage
#@ stub uloc_getLineOrientation
#@ stub uloc_getLocaleForLCID
#@ stub uloc_getName
#@ stub uloc_getParent
#@ stub uloc_getScript
#@ stub uloc_getVariant
#@ stub uloc_isRightToLeft
#@ stub uloc_minimizeSubtags
#@ stub uloc_openAvailableByType
#@ stub uloc_openKeywords
#@ stub uloc_setDefault
#@ stub uloc_setKeywordValue
#@ stub uloc_toLanguageTag
#@ stub uloc_toLegacyKey
#@ stub uloc_toLegacyType
#@ stub uloc_toUnicodeLocaleKey
#@ stub uloc_toUnicodeLocaleType
#@ stub ulocdata_close
#@ stub ulocdata_getCLDRVersion
#@ stub ulocdata_getDelimiter
#@ stub ulocdata_getExemplarSet
#@ stub ulocdata_getLocaleDisplayPattern
#@ stub ulocdata_getLocaleSeparator
#@ stub ulocdata_getMeasurementSystem
#@ stub ulocdata_getNoSubstitute
#@ stub ulocdata_getPaperSize
#@ stub ulocdata_open
#@ stub ulocdata_setNoSubstitute
#@ stub umsg_applyPattern
#@ stub umsg_autoQuoteApostrophe
#@ stub umsg_clone
#@ stub umsg_close
#@ stub umsg_format
#@ stub umsg_getLocale
#@ stub umsg_open
#@ stub umsg_parse
#@ stub umsg_setLocale
#@ stub umsg_toPattern
#@ stub umsg_vformat
#@ stub umsg_vparse
#@ stub umutablecptrie_buildImmutable
#@ stub umutablecptrie_clone
#@ stub umutablecptrie_close
#@ stub umutablecptrie_fromUCPMap
#@ stub umutablecptrie_fromUCPTrie
#@ stub umutablecptrie_get
#@ stub umutablecptrie_getRange
#@ stub umutablecptrie_open
#@ stub umutablecptrie_set
#@ stub umutablecptrie_setRange
#@ stub unorm2_append
#@ stub unorm2_close
#@ stub unorm2_composePair
#@ stub unorm2_getCombiningClass
#@ stub unorm2_getDecomposition
#@ stub unorm2_getInstance
#@ stub unorm2_getNFCInstance
#@ stub unorm2_getNFDInstance
#@ stub unorm2_getNFKCCasefoldInstance
#@ stub unorm2_getNFKCInstance
#@ stub unorm2_getNFKDInstance
#@ stub unorm2_getRawDecomposition
#@ stub unorm2_hasBoundaryAfter
#@ stub unorm2_hasBoundaryBefore
#@ stub unorm2_isInert
#@ stub unorm2_isNormalized
#@ stub unorm2_normalize
#@ stub unorm2_normalizeSecondAndAppend
#@ stub unorm2_openFiltered
#@ stub unorm2_quickCheck
#@ stub unorm2_spanQuickCheckYes
#@ stub unorm_compare
#@ stub unum_applyPattern
#@ stub unum_clone
#@ stub unum_close
#@ stub unum_countAvailable
#@ stub unum_format
#@ stub unum_formatDecimal
#@ stub unum_formatDouble
#@ stub unum_formatDoubleCurrency
#@ stub unum_formatDoubleForFields
#@ stub unum_formatInt64
#@ stub unum_formatUFormattable
#@ stub unum_getAttribute
#@ stub unum_getAvailable
#@ stub unum_getContext
#@ stub unum_getDoubleAttribute
#@ stub unum_getLocaleByType
#@ stub unum_getSymbol
#@ stub unum_getTextAttribute
#@ stub unum_open
#@ stub unum_parse
#@ stub unum_parseDecimal
#@ stub unum_parseDouble
#@ stub unum_parseDoubleCurrency
#@ stub unum_parseInt64
#@ stub unum_parseToUFormattable
#@ stub unum_setAttribute
#@ stub unum_setContext
#@ stub unum_setDoubleAttribute
#@ stub unum_setSymbol
#@ stub unum_setTextAttribute
#@ stub unum_toPattern
#@ stub unumf_close
#@ stub unumf_closeResult
#@ stub unumf_formatDecimal
#@ stub unumf_formatDouble
#@ stub unumf_formatInt
#@ stub unumf_openForSkeletonAndLocale
#@ stub unumf_openForSkeletonAndLocaleWithError
#@ stub unumf_openResult
#@ stub unumf_resultAsValue
#@ stub unumf_resultGetAllFieldPositions
#@ stub unumf_resultNextFieldPosition
#@ stub unumf_resultToString
#@ stub unumsys_close
#@ stub unumsys_getDescription
#@ stub unumsys_getName
#@ stub unumsys_getRadix
#@ stub unumsys_isAlgorithmic
#@ stub unumsys_open
#@ stub unumsys_openAvailableNames
#@ stub unumsys_openByName
#@ stub uplrules_close
#@ stub uplrules_getKeywords
#@ stub uplrules_open
#@ stub uplrules_openForType
#@ stub uplrules_select
#@ stub uplrules_selectFormatted
#@ stub uregex_appendReplacement
#@ stub uregex_appendReplacementUText
#@ stub uregex_appendTail
#@ stub uregex_appendTailUText
#@ stub uregex_clone
#@ stub uregex_close
#@ stub uregex_end
#@ stub uregex_end64
#@ stub uregex_find
#@ stub uregex_find64
#@ stub uregex_findNext
#@ stub uregex_flags
#@ stub uregex_getFindProgressCallback
#@ stub uregex_getMatchCallback
#@ stub uregex_getStackLimit
#@ stub uregex_getText
#@ stub uregex_getTimeLimit
#@ stub uregex_getUText
#@ stub uregex_group
#@ stub uregex_groupCount
#@ stub uregex_groupNumberFromCName
#@ stub uregex_groupNumberFromName
#@ stub uregex_groupUText
#@ stub uregex_hasAnchoringBounds
#@ stub uregex_hasTransparentBounds
#@ stub uregex_hitEnd
#@ stub uregex_lookingAt
#@ stub uregex_lookingAt64
#@ stub uregex_matches
#@ stub uregex_matches64
#@ stub uregex_open
#@ stub uregex_openC
#@ stub uregex_openUText
#@ stub uregex_pattern
#@ stub uregex_patternUText
#@ stub uregex_refreshUText
#@ stub uregex_regionEnd
#@ stub uregex_regionEnd64
#@ stub uregex_regionStart
#@ stub uregex_regionStart64
#@ stub uregex_replaceAll
#@ stub uregex_replaceAllUText
#@ stub uregex_replaceFirst
#@ stub uregex_replaceFirstUText
#@ stub uregex_requireEnd
#@ stub uregex_reset
#@ stub uregex_reset64
#@ stub uregex_setFindProgressCallback
#@ stub uregex_setMatchCallback
#@ stub uregex_setRegion
#@ stub uregex_setRegion64
#@ stub uregex_setRegionAndStart
#@ stub uregex_setStackLimit
#@ stub uregex_setText
#@ stub uregex_setTimeLimit
#@ stub uregex_setUText
#@ stub uregex_split
#@ stub uregex_splitUText
#@ stub uregex_start
#@ stub uregex_start64
#@ stub uregex_useAnchoringBounds
#@ stub uregex_useTransparentBounds
#@ stub uregion_areEqual
#@ stub uregion_contains
#@ stub uregion_getAvailable
#@ stub uregion_getContainedRegions
#@ stub uregion_getContainedRegionsOfType
#@ stub uregion_getContainingRegion
#@ stub uregion_getContainingRegionOfType
#@ stub uregion_getNumericCode
#@ stub uregion_getPreferredValues
#@ stub uregion_getRegionCode
#@ stub uregion_getRegionFromCode
#@ stub uregion_getRegionFromNumericCode
#@ stub uregion_getType
#@ stub ureldatefmt_close
#@ stub ureldatefmt_closeResult
#@ stub ureldatefmt_combineDateAndTime
#@ stub ureldatefmt_format
#@ stub ureldatefmt_formatNumeric
#@ stub ureldatefmt_formatNumericToResult
#@ stub ureldatefmt_formatToResult
#@ stub ureldatefmt_open
#@ stub ureldatefmt_openResult
#@ stub ureldatefmt_resultAsValue
#@ stub ures_close
#@ stub ures_getBinary
#@ stub ures_getByIndex
#@ stub ures_getByKey
#@ stub ures_getInt
#@ stub ures_getIntVector
#@ stub ures_getKey
#@ stub ures_getLocaleByType
#@ stub ures_getNextResource
#@ stub ures_getNextString
#@ stub ures_getSize
#@ stub ures_getString
#@ stub ures_getStringByIndex
#@ stub ures_getStringByKey
#@ stub ures_getType
#@ stub ures_getUInt
#@ stub ures_getUTF8String
#@ stub ures_getUTF8StringByIndex
#@ stub ures_getUTF8StringByKey
#@ stub ures_getVersion
#@ stub ures_hasNext
#@ stub ures_open
#@ stub ures_openAvailableLocales
#@ stub ures_openDirect
#@ stub ures_openU
#@ stub ures_resetIterator
#@ stub uscript_breaksBetweenLetters
#@ stub uscript_getCode
#@ stub uscript_getName
#@ stub uscript_getSampleString
#@ stub uscript_getScript
#@ stub uscript_getScriptExtensions
#@ stub uscript_getShortName
#@ stub uscript_getUsage
#@ stub uscript_hasScript
#@ stub uscript_isCased
#@ stub uscript_isRightToLeft
#@ stub usearch_close
#@ stub usearch_first
#@ stub usearch_following
#@ stub usearch_getAttribute
#@ stub usearch_getBreakIterator
#@ stub usearch_getCollator
#@ stub usearch_getMatchedLength
#@ stub usearch_getMatchedStart
#@ stub usearch_getMatchedText
#@ stub usearch_getOffset
#@ stub usearch_getPattern
#@ stub usearch_getText
#@ stub usearch_last
#@ stub usearch_next
#@ stub usearch_open
#@ stub usearch_openFromCollator
#@ stub usearch_preceding
#@ stub usearch_previous
#@ stub usearch_reset
#@ stub usearch_setAttribute
#@ stub usearch_setBreakIterator
#@ stub usearch_setCollator
#@ stub usearch_setOffset
#@ stub usearch_setPattern
#@ stub usearch_setText
#@ stub uset_add
#@ stub uset_addAll
#@ stub uset_addAllCodePoints
#@ stub uset_addRange
#@ stub uset_addString
#@ stub uset_applyIntPropertyValue
#@ stub uset_applyPattern
#@ stub uset_applyPropertyAlias
#@ stub uset_charAt
#@ stub uset_clear
#@ stub uset_clone
#@ stub uset_cloneAsThawed
#@ stub uset_close
#@ stub uset_closeOver
#@ stub uset_compact
#@ stub uset_complement
#@ stub uset_complementAll
#@ stub uset_contains
#@ stub uset_containsAll
#@ stub uset_containsAllCodePoints
#@ stub uset_containsNone
#@ stub uset_containsRange
#@ stub uset_containsSome
#@ stub uset_containsString
#@ stub uset_equals
#@ stub uset_freeze
#@ stub uset_getItem
#@ stub uset_getItemCount
#@ stub uset_getSerializedRange
#@ stub uset_getSerializedRangeCount
#@ stub uset_getSerializedSet
#@ stub uset_indexOf
#@ stub uset_isEmpty
#@ stub uset_isFrozen
#@ stub uset_open
#@ stub uset_openEmpty
#@ stub uset_openPattern
#@ stub uset_openPatternOptions
#@ stub uset_remove
#@ stub uset_removeAll
#@ stub uset_removeAllStrings
#@ stub uset_removeRange
#@ stub uset_removeString
#@ stub uset_resemblesPattern
#@ stub uset_retain
#@ stub uset_retainAll
#@ stub uset_serialize
#@ stub uset_serializedContains
#@ stub uset_set
#@ stub uset_setSerializedToOne
#@ stub uset_size
#@ stub uset_span
#@ stub uset_spanBack
#@ stub uset_spanBackUTF8
#@ stub uset_spanUTF8
#@ stub uset_toPattern
#@ stub uspoof_areConfusable
#@ stub uspoof_areConfusableUTF8
#@ stub uspoof_check
#@ stub uspoof_check2
#@ stub uspoof_check2UTF8
#@ stub uspoof_checkUTF8
#@ stub uspoof_clone
#@ stub uspoof_close
#@ stub uspoof_closeCheckResult
#@ stub uspoof_getAllowedChars
#@ stub uspoof_getAllowedLocales
#@ stub uspoof_getCheckResultChecks
#@ stub uspoof_getCheckResultNumerics
#@ stub uspoof_getCheckResultRestrictionLevel
#@ stub uspoof_getChecks
#@ stub uspoof_getInclusionSet
#@ stub uspoof_getRecommendedSet
#@ stub uspoof_getRestrictionLevel
#@ stub uspoof_getSkeleton
#@ stub uspoof_getSkeletonUTF8
#@ stub uspoof_open
#@ stub uspoof_openCheckResult
#@ stub uspoof_openFromSerialized
#@ stub uspoof_openFromSource
#@ stub uspoof_serialize
#@ stub uspoof_setAllowedChars
#@ stub uspoof_setAllowedLocales
#@ stub uspoof_setChecks
#@ stub uspoof_setRestrictionLevel
#@ stub usprep_close
#@ stub usprep_open
#@ stub usprep_openByType
#@ stub usprep_prepare
#@ stub utext_char32At
#@ stub utext_clone
#@ stub utext_close
#@ stub utext_copy
#@ stub utext_current32
#@ stub utext_equals
#@ stub utext_extract
#@ stub utext_freeze
#@ stub utext_getNativeIndex
#@ stub utext_getPreviousNativeIndex
#@ stub utext_hasMetaData
#@ stub utext_isLengthExpensive
#@ stub utext_isWritable
#@ stub utext_moveIndex32
#@ stub utext_nativeLength
#@ stub utext_next32
#@ stub utext_next32From
#@ stub utext_openUChars
#@ stub utext_openUTF8
#@ stub utext_previous32
#@ stub utext_previous32From
#@ stub utext_replace
#@ stub utext_setNativeIndex
#@ stub utext_setup
#@ stub utf8_appendCharSafeBody
#@ stub utf8_back1SafeBody
#@ stub utf8_nextCharSafeBody
#@ stub utf8_prevCharSafeBody
#@ stub utmscale_fromInt64
#@ stub utmscale_getTimeScaleValue
#@ stub utmscale_toInt64
#@ stub utrace_format
#@ stub utrace_functionName
#@ stub utrace_getFunctions
#@ stub utrace_getLevel
#@ stub utrace_setFunctions
#@ stub utrace_setLevel
#@ stub utrace_vformat
#@ stub utrans_clone
#@ stub utrans_close
#@ stub utrans_countAvailableIDs
#@ stub utrans_getSourceSet
#@ stub utrans_getUnicodeID
#@ stub utrans_openIDs
#@ stub utrans_openInverse
#@ stub utrans_openU
#@ stub utrans_register
#@ stub utrans_setFilter
#@ stub utrans_toRules
#@ stub utrans_trans
#@ stub utrans_transIncremental
#@ stub utrans_transIncrementalUChars
#@ stub utrans_transUChars
#@ stub utrans_unregisterID
