@ stdcall agsDeInit(ptr)
@ stdcall agsCheckDriverVersion(ptr long)
@ stub agsDriverExtensionsDX11_BeginUAVOverlap
@ stub agsDriverExtensionsDX11_CreateBuffer
@ stub agsDriverExtensionsDX11_CreateDevice
@ stub agsDriverExtensionsDX11_CreateFromDevice
@ stub agsDriverExtensionsDX11_CreateTexture1D
@ stub agsDriverExtensionsDX11_CreateTexture2D
@ stub agsDriverExtensionsDX11_CreateTexture3D
@ stub agsDriverExtensionsDX11_DeInit
@ stub agsDriverExtensionsDX11_Destroy
@ stub agsDriverExtensionsDX11_DestroyDevice
@ stub agsDriverExtensionsDX11_EndUAVOverlap
@ stub agsDriverExtensionsDX11_GetMaxClipRects
@ stub agsDriverExtensionsDX11_IASetPrimitiveTopology
@ stub agsDriverExtensionsDX11_Init
@ stub agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect
@ stub agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect
@ stub agsDriverExtensionsDX11_MultiDrawInstancedIndirect
@ stub agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect
@ stub agsDriverExtensionsDX11_NotifyResourceBeginAllAccess
@ stub agsDriverExtensionsDX11_NotifyResourceEndAllAccess
@ stub agsDriverExtensionsDX11_NotifyResourceEndWrites
@ stub agsDriverExtensionsDX11_NumPendingAsyncCompileJobs
@ stub agsDriverExtensionsDX11_SetClipRects
@ stub agsDriverExtensionsDX11_SetDepthBounds
@ stub agsDriverExtensionsDX11_SetDiskShaderCacheEnabled
@ stub agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount
@ stub agsDriverExtensionsDX11_SetViewBroadcastMasks
@ stub agsDriverExtensionsDX11_WriteBreadcrumb
@ stdcall agsDriverExtensionsDX12_CreateDevice(ptr ptr ptr ptr)
@ stub agsDriverExtensionsDX12_CreateFromDevice
@ stub agsDriverExtensionsDX12_DeInit
@ stub agsDriverExtensionsDX12_Destroy
@ stdcall agsDriverExtensionsDX12_DestroyDevice(ptr ptr ptr)
@ stub agsDriverExtensionsDX12_Init
@ stub agsDriverExtensionsDX12_PopMarker
@ stub agsDriverExtensionsDX12_PushMarker
@ stub agsDriverExtensionsDX12_SetMarker
@ stdcall agsGetCrossfireGPUCount(ptr ptr)
@ stdcall agsInit(ptr ptr ptr)
@ stub agsSetDisplayMode
