noinst_LTLIBRARIES = libgoliath_common.la

libgoliath_common_la_SOURCES = \
        debug.c \
        error.c \
        memory.c \
        path.c \
        string.c \
        util.c

noinst_HEADERS = \
        debug.h \
        error.h \
        memory.h \
        path.h \
        string.h \
        util.h

AM_CFLAGS = -I$(top_srcdir)/include
AM_CPPFLAGS = -I$(top_srcdir)/include
